### PR TITLE
Fix misplaced uan of `dCKB` and `YOK`

### PR DESCRIPTION
**Pull request by ShookLyngs**
### Description

The UANs of `dCKB` (mainnet_v1) are incorrectly defined as: 
- `L1UAN` - YOK.ckb
- `L2UAN` - YOK.gw|gb.ckb

This makes `dCKB` and `YOK` share the same UANs, and can cause serious mistakes in the L1-Transfer page (displaying the wrong balance or choosing the wrong token since L1-Transfer page is using UAN as ID), which should be fixed by this PR. 

### Related issues
- https://github.com/godwokenrises/light-godwoken/issues/223
  Thanks to @Dawn-githup for spotting the issue.

### CODE REVIEW

**Review by Flouse — COMMENTED** [review]
missing dCKB's layer1DisplayName and layer2DisplayName

**Comment by ShookLyngs** [comment]
> missing dCKB's layer1DisplayName and layer2DisplayName

Fixed in [86bc7c7ff](https://github.com/godwokenrises/light-godwoken/pull/224/commits/82bbd919faf96e454beeb1a4896e16da6bc7c7ff).

**Review by Dawn-githup — APPROVED** [review]

**Comment by Dawn-githup** [comment]
https://github.com/godwokenrises/light-godwoken/issues/226

**Comment by ShookLyngs** [comment]
> L1 Transfer Completed list is missing the success identifier #226

Not the same type of issue, I will open a new PR for this issue.

**Review by Flouse — APPROVED** [review]

**Pull request merged**
