### PR TITLE
fix: UI&UX adjustment of network mismatch notification

### LINKED ISSUE #269: Confirm button in the Network Mismatch dialog does not respond
The `Confirm` button does not work when the current network is matched to the bridge. How to reproduce:
1. Switch to any network but `Godowken Testnet V1` in MetaMask
2. Open Godwoken Bridge Testnet (https://testnet.bridge.godwoken.io)
3. When the Network Mismatch dialog pops up, switch to `Godwoken Testnet V1` in MetaMask
4. Click the `Confirm` button in the Network Mismatch dialog, nothing happens

### LINKED ISSUE #270: The intra-application network switching strategy is too radical
1.Currently applied to network mismatch
2.Turn off the prompt of switching network within the application and switch to other pages within the application
3.You should not prompt frequently when switching pages within the application

image

### PR DESCRIPTION
**Pull request by GitOfJason**
### Changed
- Adjust the listening location of the onChainChange event
- Optimize the notification UI interaction when the network does not match, and no longer display the notification in the pop-up window mode to reduce the interference to user operation

### Related problem
- fix #269 
- fix #270

### CODE REVIEW

**Comment by ShookLyngs** [comment]
From my perspective, the alert style in desktop mode is cool, but in mobile mode it is a bit off.
How do you guys think, can you read the alert message clearly? @Dawn-githup @Flouse

image

**Comment by Dawn-githup** [comment]
> From my perspective, the alert style in desktop mode is cool, but in mobile mode it is a bit difficult to read. How do you guys think, can you read the alert message clearly? @Dawn-githup @Flouse
> 
> image
image

The readability is not very user-friendly, and it's difficult to standardize the format considering the different sizes of mobile screens.

**Comment by GitOfJason** [comment]
image

Would that make it any better?
@ShookLyngs @Dawn-githup

**Comment by GitOfJason** [comment]
Or a simpler way

截屏2023-02-17 16 15 24
截屏2023-02-17 16 15 36

**Comment by Flouse** [comment]
image
https://godwoken-bridge-mainnet-90y3kdj2l-godwoken.vercel.app

After switching to Godwoken mainnet_v1, the <SimpleAlert> component did not dispear.

## Error in [Brave](https://brave.com/) browser console
```
Error: underlying network changed (event="changed", network={"chainId":71394,"name":"unknown"}, detectedNetwork={"chainId":71402,"name":"unknown"}, code=NETWORK_ERROR, version=providers/5.6.8)
```
image

**Comment by GitOfJason** [comment]
> image https://godwoken-bridge-mainnet-90y3kdj2l-godwoken.vercel.app
> 
> After switching to Godwoken mainnet_v1, the component did not disappear.
> 
> ## Error in [Brave](https://brave.com/) browser console
> ```
> Error: underlying network changed (event="changed", network={"chainId":71394,"name":"unknown"}, detectedNetwork={"chainId":71402,"name":"unknown"}, code=NETWORK_ERROR, version=providers/5.6.8)
> ```
> 
> image

Use the same browser, but can't reproduce your problem. Is there a reproducible path?

**Comment by ShookLyngs** [comment]
@GitOfJason @Dawn-githup An advice, removing the title in the component was nice, I've also adjusted some colors/background-colors of the component, `text-align` is set to `center` in mobile mode, is it better or worse? I'm not sure what was wrong. If you guys think the current style is better, I can approve the PR.

image
image

**Comment by GitOfJason** [comment]
> @GitOfJason @Dawn-githup An advice, removing the title in the component was nice, I've also adjusted some colors/background-colors of the component, `text-align` is set to `center` in mobile mode, is it better or worse? I'm not sure what was wrong. If you guys think the current style is better, I can approve the PR.
> 
> image image

I don't have any more suggestions on style, but I still need to verify @flouse problem. When there is no problem, I will launch a review again . @ShookLyngs cc

**Comment by Dawn-githup** [comment]
> > @GitOfJason @Dawn-githup An advice, removing the title in the component was nice, I've also adjusted some colors/background-colors of the component, `text-align` is set to `center` in mobile mode, is it better or worse? I'm not sure what was wrong. If you guys think the current style is better, I can approve the PR.
> > image image
> 
> I don't have any more suggestions on style, but I still need to verify @Flouse problem. When there is no problem, I will launch a review again . @ShookLyngs cc

I can't reproduce the problem of @Flouse locally flouse Can you describe the specific characteristics of recurrence

**Comment by Dawn-githup** [comment]
> > @GitOfJason @Dawn-githup An advice, removing the title in the component was nice, I've also adjusted some colors/background-colors of the component, `text-align` is set to `center` in mobile mode, is it better or worse? I'm not sure what was wrong. If you guys think the current style is better, I can approve the PR.
> > image image
> 
> I don't have any more suggestions on style, but I still need to verify @Flouse problem. When there is no problem, I will launch a review again . @ShookLyngs cc

I can't reproduce Flouse's problem locally. @ Flouse can you describe the characteristics of recurrence

**Comment by Flouse** [comment]
Here is a real usage scenario.

1. visit https://v0.yokaiswap.com
    and the network will be switched to Godwoken v0
    
2. visit https://godwoken-bridge-mainnet-bwzolkqo0-godwoken.vercel.app 
    image
   a. Godwoken Bridge told me to switch network, I switched the network to Godwoken mainnet_v1 on Metamask.
   b. After switching to Godwoken mainnet_v1, the component disappear now.
   
   
---
So, it works for me now.

**Review by Flouse — APPROVED** [review]

**Comment by GitOfJason** [comment]
UI has been modified to your suggestions @ShookLyngs

**Review by Dawn-githup — APPROVED** [review]

**Review by Flouse — APPROVED** [review]

**Pull request merged**
