### PR TITLE
chore: create-react migration to vite

### PR DESCRIPTION
**Pull request by frmachao**
### 主要改动

1. 将 apps/godwoken-bridge 项目从 create-react 迁移到 vite，来获得更好的开发体验
 
迁移前后对比：

  | 启动用时 | 构建用时 | 热更新
-- | -- | -- | --
Vite | 368ms | 27s | 毫秒级
CRA | 23s | 38s | 1~2秒

### 界面截图

image

image

image

### 检查清单

- [x]  apps/godwoken-bridge 项目应该可以正常 start
- [x]  apps/godwoken-bridge 项目应该可以正常 build

### CODE REVIEW

**Review by ShookLyngs — CHANGES_REQUESTED** [review]
Great work, apparently Vite is a better choice for building spa these days, and the pull request does its job with minimal cost. However, there is an issue that needs to be fixed: types for `vite` and `svrg` are now missing, so `tsc` command cannot pass, you can fix them by adding the following declarations to the project:
```typescript
/// <reference types="vite/client" />
/// <reference types="vite-plugin-svgr/client" />
```

One more thing, since we are moving from `cra` to `vite`, maybe the `react-app-env.d.ts` file is no longer needed?

**Review by Dawn-githup — APPROVED** [review]

**Review by ShookLyngs — APPROVED** [review]

**Comment by ShookLyngs** [comment]
@frmachao @Flouse #290 has been merged before this, maybe we need a rebase?

**Review by GitOfJason — APPROVED** [review]

**Comment by Flouse** [comment]
> @frmachao @Flouse #290 has been merged before this, maybe we need a rebase?

yep, it requires a git rebase.
The plan is to include this PR in the next mirror release, and we can do a git rebase before then.

**Comment by frmachao** [comment]
> 



> > @frmachao @Flouse #290 has been merged before this, maybe we need a rebase?
> 
> yep, it requires a git rebase. The plan is to include this PR in the next mirror release, and we can do a git rebase before then.

Okay, I'll take care of it.

**Comment by frmachao** [comment]
git rebase is done @Flouse

**Review by Dawn-githup — APPROVED** [review]

**Comment by frmachao** [comment]
error Your lockfile needs to be updated, but yarn was run with `–frozen-lockfile`.
solution: Just run the `yarn install` command to update the yarn.lock file.

All tests have been passed @Flouse

**Review by ShookLyngs — APPROVED** [review]

**Comment by Flouse** [comment]
> error Your lockfile needs to be updated, but yarn was run with `–frozen-lockfile`. solution: Just run the `yarn install` command to update the yarn.lock file.
> 
> All tests have been passed @Flouse

Thank you!

**Pull request merged**
