### PR TITLE
Support dotbit forward/reverse search features

### PR DESCRIPTION
**Pull request by ShookLyngs**
### Description
Added .bit forward/reverse search features to godwoken-bridge.
Now you should be able to:
- `Reverse search` - Check your .bit alias (search by your ETH address)
- `Forward search` - When L1 transferring, you can enter a .bit account, and then select a related address of the .bit account, instead of directly entering the receiver's CKB address

### Details
- **What is .bit**
  DotBit (or .bit) is a cross-chain Web3 identity management platform. We can bind our ETH/CKB address to a .bit account to facilitate others to find our address. For more details please check: [.bit](https://www.did.id/).

- **Reverse searching**
  Reverse search is a feature for you to search for an address and get the .bit account of the address. For instance, you can reverse search for `0x....` (an ETH address) to get its .bit account `test.bit`.
  One thing to be noted, right now .bit alias only supports ETH/BSC/TRX/Polygon addresses bound to .bit accounts, so we can reverse search for an ETH address and get its .bit account, but we cannot reverse search for a CKB address and get its .bit account.

- **Forward searching**
  Forward search is a feature that allows you to search for .bit accounts, and get the data associated with them. For instance, you can forward search for `test.bit` and get its related addresses: [test.bit on .bit](https://data.did.id/test.bit).
  On godwoken-bridge, previously when we want to transfer assets to others on L1, we need to paste the recipient's CKB address into the input, the address is always long and hard to remember it all. Now we can enter the recipient's .bit account in the input, and select the recipient's address to transfer to it.

- **Converting addresses in forward search**
  On .bit data we can bind the addresses of many chains, but on l1-transfer page of godwoken-bridge we can only transfer to CKB addresses. So for CKB addresses in the .bit data we can transfer to them directly, and for ETH addresses, we can convert them to Omni-Lock CKB Addresses, and them transfer to those addresses. As to addresses other than ETH/CKB are not supported for the moment.
  For this reason, in l1-transfer page, when we selected an ETH address, we're actually gonna transfer assets to the ETH address' Omni-Lock CKB Address, which is the same concept as `L1 Wallet Address` on godwoken-bridge.
  For more details about Omni-Lock, please check RFC: [Omnilock](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0042-omnilock/0042-omnilock.md).

- **Differences on mainnet/testnet**
  Since .bit only supports CKB mainnet, therefore on godwoken-bridge mainnet, we can select ETH/CKB addresses in .bit data, but on godwoken-bridge testnet, we can only select ETH addresses in .bit data.

### CODE REVIEW

**Comment by ShookLyngs** [comment]
Added `label` to dotbit address options, to help users distinguish addresses. 
Thanks to @Dawn-githup for the advice.

image

**Review by classicalliu — APPROVED** [review]

**Comment by Dawn-githup** [comment]
image

**Comment by Dawn-githup** [comment]
The mainnet website preview access link has a faucet

**Comment by ShookLyngs** [comment]
> image

The issue is now fixed, thanks for pointing it out.

**Review by Dawn-githup — APPROVED** [review]

**Review by Flouse — APPROVED** [review]

**Pull request merged**
