### PR TITLE
chore: bump v0.4.0

### PR DESCRIPTION
**Pull request by ShookLyngs**
Planning to release the `0.4.0` version of light-godwoken tomorrow. This is a version with some breaking changes, and we have new contributors addressing many of our issues, thanks to @GitOfJason @miaosun009. 

Also, while editing the changelog, a question came to my mind: we have so many changes in this version, it would be a little hard to mention contributors for each pull request like before, so should we find a better/simpler way to mention contributions in our changelog?

Here's an example of how we mention a contributor before:
```markdown
- Describe the change (pull/issue number)
> Thanks to @thecontributor for contributing the PR
```

Should we find a simpler way to do it? Like so:
```markdown
- Describe the change (pull/issue number) (@thecontributor)
```

### CODE REVIEW

**Comment by Flouse** [comment]
> Should we find a simpler way to do it? Like so:
> 
> ```gfm
> - Describe the change (pull/issue number) (@thecontributor)
> ```

LGTM.
You could generate the release note draft by https://github.com/godwokenrises/light-godwoken/releases/new
image

**Review by Flouse — APPROVED** [review]

**Comment by ShookLyngs** [comment]
The changelog is updated with a new format to mention contributors.

**Review by GitOfJason — APPROVED** [review]

**Comment by Dawn-githup** [comment]
I encountered an error while depositing
```
instrument.ts:124 Error: {"code":-301,"message":"TransactionFailedToResolve: Resolve failed Unknown(OutPoint(0x33d7fd2c618e1788c872c8464b8bea2a9d7330983bcc106fdb9e2d045da8552a02000000))","data":"Resolve(Unknown(OutPoint(0x33d7fd2c618e1788c872c8464b8bea2a9d7330983bcc106fdb9e2d045da8552a02000000)))"}
    at method.ts:58:15
```

**Review by Dawn-githup — APPROVED** [review]

**Comment by ShookLyngs** [comment]
> I encountered an error while depositing

Me and @Dawn-githup has a discussion about this error, and it is due to input cells being reused in consecutive transactions. Therefore it has no related to this PR.

**Pull request merged**
